# Generated by Django 5.0.6 on 2025-10-22 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('overall_sentiment', models.CharField(max_length=20)),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('market_outlook', models.TextField()),
                ('articles_analyzed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sentiment Analyses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(choices=[('coindesk', 'CoinDesk'), ('cointelegraph', 'CoinTelegraph'), ('yahoo_finance', 'Yahoo Finance')], max_length=50)),
                ('text', models.TextField()),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['-scraped_at'], name='news_newsar_scraped_f9f946_idx'), models.Index(fields=['sentiment'], name='news_newsar_sentime_3faad7_idx'), models.Index(fields=['source'], name='news_newsar_source_2a5eed_idx')],
            },
        ),
    ]
